---
- name: Login to dockerHub
  docker_login:
    username: aminemokaddem
    password: 18mbqncmine
    reauthorize: yes
- name: Tag and push to docker hub
  docker_image:
    name: aminemokaddem/devops
    repository: aminemokaddem/devops
    tag: latest
    push: yes
    source: local

